[2020-06-05 16:18:31,252] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_india_dag.upload_status_to_table 2020-06-05T10:46:11.120379+00:00 [queued]>
[2020-06-05 16:18:31,262] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_india_dag.upload_status_to_table 2020-06-05T10:46:11.120379+00:00 [queued]>
[2020-06-05 16:18:31,262] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-05 16:18:31,262] {taskinstance.py:880} INFO - Starting attempt 1 of 2
[2020-06-05 16:18:31,262] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-05 16:18:31,272] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): upload_status_to_table> on 2020-06-05T10:46:11.120379+00:00
[2020-06-05 16:18:31,278] {standard_task_runner.py:53} INFO - Started process 18185 to run task
[2020-06-05 16:18:31,332] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: covid_india_dag.upload_status_to_table 2020-06-05T10:46:11.120379+00:00 [running]> nineleaps-ThinkPad-L470
[2020-06-05 16:18:32,619] {logging_mixin.py:112} INFO - [2020-06-05 16:18:32,619] {Covid_India_SampleDag.py:97} ERROR - Reason: 404 Not found: Table bigquerytest-271705:Covid19.test was not found in location US

(job ID: c6387c3d-c7c8-44c3-893b-b1008f38f1a5)

          -----Query Job SQL Follows-----           

    |    .    |    .    |    .    |    .    |
   1:select count(*) as total_rows from Covid19.test
    |    .    |    .    |    .    |    .    |
[2020-06-05 16:18:41,255] {logging_mixin.py:112} INFO - [2020-06-05 16:18:41,254] {local_task_job.py:103} INFO - Task exited with return code 0
