[2020-06-05 16:20:22,599] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_india_dag.upload_status_to_table 2020-06-05T10:46:11.120379+00:00 [queued]>
[2020-06-05 16:20:22,618] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_india_dag.upload_status_to_table 2020-06-05T10:46:11.120379+00:00 [queued]>
[2020-06-05 16:20:22,618] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-05 16:20:22,618] {taskinstance.py:880} INFO - Starting attempt 2 of 2
[2020-06-05 16:20:22,618] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-05 16:20:22,629] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): upload_status_to_table> on 2020-06-05T10:46:11.120379+00:00
[2020-06-05 16:20:22,632] {standard_task_runner.py:53} INFO - Started process 18379 to run task
[2020-06-05 16:20:22,682] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: covid_india_dag.upload_status_to_table 2020-06-05T10:46:11.120379+00:00 [running]> nineleaps-ThinkPad-L470
[2020-06-05 16:20:24,112] {logging_mixin.py:112} INFO - [2020-06-05 16:20:24,111] {Covid_India_SampleDag.py:97} ERROR - Reason: 404 Not found: Table bigquerytest-271705:Covid19.test was not found in location US

(job ID: f3498454-052e-4e8e-ba91-e0c43a5af262)

          -----Query Job SQL Follows-----           

    |    .    |    .    |    .    |    .    |
   1:select count(*) as total_rows from Covid19.test
    |    .    |    .    |    .    |    .    |
[2020-06-05 16:20:32,583] {logging_mixin.py:112} INFO - [2020-06-05 16:20:32,583] {local_task_job.py:103} INFO - Task exited with return code 0
