[2020-06-03 12:28:00,077] {logging_mixin.py:112} INFO - Sending to executor.
[2020-06-03 12:28:00,078] {logging_mixin.py:112} INFO - [2020-06-03 12:28:00,077] {base_executor.py:58} INFO - Adding to queue: ['airflow', 'run', 'covid_dag', 'source_to_csv', '2020-06-03T00:00:00+00:00', '--local', '--pool', 'default_pool', '-sd', 'DAGS_FOLDER/covid_dag.py']
[2020-06-03 12:28:00,078] {logging_mixin.py:112} INFO - [2020-06-03 12:28:00,078] {sequential_executor.py:45} INFO - Executing command: ['airflow', 'run', 'covid_dag', 'source_to_csv', '2020-06-03T00:00:00+00:00', '--local', '--pool', 'default_pool', '-sd', 'DAGS_FOLDER/covid_dag.py']
[2020-06-03 12:28:01,682] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_dag.source_to_csv 2020-06-03T00:00:00+00:00 [None]>
[2020-06-03 12:28:01,687] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_dag.source_to_csv 2020-06-03T00:00:00+00:00 [None]>
[2020-06-03 12:28:01,687] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-03 12:28:01,688] {taskinstance.py:880} INFO - Starting attempt 1 of 2
[2020-06-03 12:28:01,688] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-03 12:28:01,695] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): source_to_csv> on 2020-06-03T00:00:00+00:00
[2020-06-03 12:28:01,697] {standard_task_runner.py:53} INFO - Started process 4218 to run task
[2020-06-03 12:28:01,732] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: covid_dag.source_to_csv 2020-06-03T00:00:00+00:00 [running]> nineleaps-ThinkPad-L470
[2020-06-03 12:28:02,155] {taskinstance.py:1145} ERROR - type object 'datetime.datetime' has no attribute 'datetime'
Traceback (most recent call last):
  File "/home/nineleaps/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/nineleaps/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/nineleaps/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/nineleaps/airflow/dags/covid_dag.py", line 33, in source_to_csv
    yest_date = datetime.datetime.now() - timedelta(days=1)
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
[2020-06-03 12:28:02,159] {taskinstance.py:1168} INFO - Marking task as UP_FOR_RETRY
[2020-06-03 12:28:11,684] {logging_mixin.py:112} INFO - [2020-06-03 12:28:11,683] {local_task_job.py:103} INFO - Task exited with return code 1
