[2020-06-05 13:56:16,049] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_india_dag.source_to_csv 2020-06-05T08:26:03.889190+00:00 [queued]>
[2020-06-05 13:56:16,055] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_india_dag.source_to_csv 2020-06-05T08:26:03.889190+00:00 [queued]>
[2020-06-05 13:56:16,055] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-05 13:56:16,055] {taskinstance.py:880} INFO - Starting attempt 1 of 2
[2020-06-05 13:56:16,055] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-05 13:56:16,062] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): source_to_csv> on 2020-06-05T08:26:03.889190+00:00
[2020-06-05 13:56:16,065] {standard_task_runner.py:53} INFO - Started process 7810 to run task
[2020-06-05 13:56:16,097] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: covid_india_dag.source_to_csv 2020-06-05T08:26:03.889190+00:00 [running]> nineleaps-ThinkPad-L470
[2020-06-05 13:56:16,899] {logging_mixin.py:112} INFO - [2020-06-05 13:56:16,897] {Covid_India_SampleDag.py:48} ERROR - Error: 404 Client Error: Not Found for url: https://api.covid19india.org/states_daily.jso
[2020-06-05 13:56:26,054] {logging_mixin.py:112} INFO - [2020-06-05 13:56:26,053] {local_task_job.py:103} INFO - Task exited with return code 0
