[2020-06-09 12:54:40,102] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_india_dag.source_to_csv 2020-06-09T07:23:55.322252+00:00 [queued]>
[2020-06-09 12:54:40,108] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_india_dag.source_to_csv 2020-06-09T07:23:55.322252+00:00 [queued]>
[2020-06-09 12:54:40,108] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-09 12:54:40,108] {taskinstance.py:880} INFO - Starting attempt 1 of 2
[2020-06-09 12:54:40,109] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-09 12:54:40,117] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): source_to_csv> on 2020-06-09T07:23:55.322252+00:00
[2020-06-09 12:54:40,122] {standard_task_runner.py:53} INFO - Started process 11959 to run task
[2020-06-09 12:54:40,157] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: covid_india_dag.source_to_csv 2020-06-09T07:23:55.322252+00:00 [running]> nineleaps-ThinkPad-L470
[2020-06-09 12:54:40,876] {logging_mixin.py:112} INFO - [2020-06-09 12:54:40,875] {covid_india_dag.py:50} ERROR - Http Error: 404 Client Error: Not Found for url: https://api.covid19india.org/states_daily.jso
[2020-06-09 12:54:40,877] {taskinstance.py:1145} ERROR - 404 Client Error: Not Found for url: https://api.covid19india.org/states_daily.jso
Traceback (most recent call last):
  File "/home/nineleaps/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/nineleaps/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/nineleaps/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/nineleaps/airflow/dags/covid_india_dag.py", line 90, in source_to_csv
    data = get_covid_data()
  File "/home/nineleaps/airflow/dags/covid_india_dag.py", line 82, in get_covid_data
    confirmed_case_df = get_confirmed_cases()
  File "/home/nineleaps/airflow/dags/covid_india_dag.py", line 39, in get_confirmed_cases
    r.raise_for_status()
  File "/home/nineleaps/.local/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.covid19india.org/states_daily.jso
[2020-06-09 12:54:40,888] {taskinstance.py:1168} INFO - Marking task as UP_FOR_RETRY
[2020-06-09 12:54:43,113] {logging_mixin.py:112} INFO - [2020-06-09 12:54:43,112] {email.py:131} INFO - Sent an alert email to ['captaincold268@gmail.com']
[2020-06-09 12:54:50,102] {logging_mixin.py:112} INFO - [2020-06-09 12:54:50,101] {local_task_job.py:103} INFO - Task exited with return code 1
