[2020-06-04 17:20:58,155] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_india_dag.source_to_csv 2020-06-04T11:50:12.364859+00:00 [queued]>
[2020-06-04 17:20:58,161] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_india_dag.source_to_csv 2020-06-04T11:50:12.364859+00:00 [queued]>
[2020-06-04 17:20:58,161] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-04 17:20:58,161] {taskinstance.py:880} INFO - Starting attempt 1 of 2
[2020-06-04 17:20:58,162] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-04 17:20:58,170] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): source_to_csv> on 2020-06-04T11:50:12.364859+00:00
[2020-06-04 17:20:58,172] {standard_task_runner.py:53} INFO - Started process 21117 to run task
[2020-06-04 17:20:58,207] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: covid_india_dag.source_to_csv 2020-06-04T11:50:12.364859+00:00 [running]> nineleaps-ThinkPad-L470
[2020-06-04 17:20:58,626] {taskinstance.py:1145} ERROR - name 'get_state_list' is not defined
Traceback (most recent call last):
  File "/home/nineleaps/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/nineleaps/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/nineleaps/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/nineleaps/airflow/dags/Covid_India_SampleDag.py", line 63, in source_to_csv
    data = get_covid_data()
  File "/home/nineleaps/airflow/dags/Covid_India_SampleDag.py", line 56, in get_covid_data
    state_list_df = get_state_list()
NameError: name 'get_state_list' is not defined
[2020-06-04 17:20:58,628] {taskinstance.py:1168} INFO - Marking task as UP_FOR_RETRY
[2020-06-04 17:21:00,531] {logging_mixin.py:112} INFO - [2020-06-04 17:21:00,530] {email.py:131} INFO - Sent an alert email to ['captaincold268@gmail.com']
[2020-06-04 17:21:08,156] {logging_mixin.py:112} INFO - [2020-06-04 17:21:08,155] {local_task_job.py:103} INFO - Task exited with return code 1
