[2020-06-04 17:22:03,615] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_india_dag.source_to_csv 2020-06-04T11:50:12.364859+00:00 [queued]>
[2020-06-04 17:22:03,624] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_india_dag.source_to_csv 2020-06-04T11:50:12.364859+00:00 [queued]>
[2020-06-04 17:22:03,625] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-04 17:22:03,625] {taskinstance.py:880} INFO - Starting attempt 2 of 2
[2020-06-04 17:22:03,625] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-04 17:22:03,634] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): source_to_csv> on 2020-06-04T11:50:12.364859+00:00
[2020-06-04 17:22:03,639] {standard_task_runner.py:53} INFO - Started process 21204 to run task
[2020-06-04 17:22:03,687] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: covid_india_dag.source_to_csv 2020-06-04T11:50:12.364859+00:00 [running]> nineleaps-ThinkPad-L470
[2020-06-04 17:22:04,093] {taskinstance.py:1145} ERROR - name 'get_state_list' is not defined
Traceback (most recent call last):
  File "/home/nineleaps/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/nineleaps/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/nineleaps/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/nineleaps/airflow/dags/Covid_India_SampleDag.py", line 63, in source_to_csv
    data = get_covid_data()
  File "/home/nineleaps/airflow/dags/Covid_India_SampleDag.py", line 56, in get_covid_data
    state_list_df = get_state_list()
NameError: name 'get_state_list' is not defined
[2020-06-04 17:22:04,095] {taskinstance.py:1187} INFO - All retries failed; marking task as FAILED.dag_id=covid_india_dag, task_id=source_to_csv, execution_date=20200604T115012, start_date=20200604T115203, end_date=20200604T115204
[2020-06-04 17:22:06,064] {logging_mixin.py:112} INFO - [2020-06-04 17:22:06,064] {email.py:131} INFO - Sent an alert email to ['captaincold268@gmail.com']
[2020-06-04 17:22:13,614] {logging_mixin.py:112} INFO - [2020-06-04 17:22:13,612] {local_task_job.py:103} INFO - Task exited with return code 1
