[2020-06-05 13:07:29,267] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_india_dag.source_to_csv 2020-06-05T07:35:17.481551+00:00 [queued]>
[2020-06-05 13:07:29,274] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_india_dag.source_to_csv 2020-06-05T07:35:17.481551+00:00 [queued]>
[2020-06-05 13:07:29,274] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-05 13:07:29,274] {taskinstance.py:880} INFO - Starting attempt 2 of 2
[2020-06-05 13:07:29,274] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-05 13:07:29,282] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): source_to_csv> on 2020-06-05T07:35:17.481551+00:00
[2020-06-05 13:07:29,284] {standard_task_runner.py:53} INFO - Started process 3701 to run task
[2020-06-05 13:07:29,317] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: covid_india_dag.source_to_csv 2020-06-05T07:35:17.481551+00:00 [running]> nineleaps-ThinkPad-L470
[2020-06-05 13:07:29,784] {logging_mixin.py:112} WARNING - --- Logging error ---
[2020-06-05 13:07:29,786] {logging_mixin.py:112} WARNING - Traceback (most recent call last):
[2020-06-05 13:07:29,786] {logging_mixin.py:112} WARNING -   File "/home/nineleaps/airflow/dags/Covid_India_SampleDag.py", line 35, in get_confirmed_cases
    r.raise_for_status()
[2020-06-05 13:07:29,786] {logging_mixin.py:112} WARNING -   File "/home/nineleaps/.local/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
[2020-06-05 13:07:29,786] {logging_mixin.py:112} WARNING - requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.covid19india.org/states_daily.jso
[2020-06-05 13:07:29,787] {logging_mixin.py:112} WARNING - 
During handling of the above exception, another exception occurred:
[2020-06-05 13:07:29,787] {logging_mixin.py:112} WARNING - Traceback (most recent call last):
[2020-06-05 13:07:29,787] {logging_mixin.py:112} WARNING -   File "/usr/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
[2020-06-05 13:07:29,787] {logging_mixin.py:112} WARNING -   File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
[2020-06-05 13:07:29,787] {logging_mixin.py:112} WARNING -   File "/home/nineleaps/.local/lib/python3.6/site-packages/airflow/utils/log/colored_log.py", line 93, in format
    return super(CustomTTYColoredFormatter, self).format(record)
[2020-06-05 13:07:29,787] {logging_mixin.py:112} WARNING -   File "/home/nineleaps/.local/lib/python3.6/site-packages/colorlog/colorlog.py", line 119, in format
    message = super(ColoredFormatter, self).format(record)
[2020-06-05 13:07:29,787] {logging_mixin.py:112} WARNING -   File "/usr/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
[2020-06-05 13:07:29,787] {logging_mixin.py:112} WARNING -   File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
[2020-06-05 13:07:29,787] {logging_mixin.py:112} WARNING - TypeError: not all arguments converted during string formatting
[2020-06-05 13:07:29,787] {logging_mixin.py:112} WARNING - Call stack:
[2020-06-05 13:07:29,792] {logging_mixin.py:112} WARNING -   File "/home/nineleaps/.local/bin/airflow", line 37, in <module>
    args.func(args)
[2020-06-05 13:07:29,792] {logging_mixin.py:112} WARNING -   File "/home/nineleaps/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 75, in wrapper
    return f(*args, **kwargs)
[2020-06-05 13:07:29,792] {logging_mixin.py:112} WARNING -   File "/home/nineleaps/.local/lib/python3.6/site-packages/airflow/bin/cli.py", line 545, in run
    _run(args, dag, ti)
[2020-06-05 13:07:29,792] {logging_mixin.py:112} WARNING -   File "/home/nineleaps/.local/lib/python3.6/site-packages/airflow/bin/cli.py", line 460, in _run
    run_job.run()
[2020-06-05 13:07:29,792] {logging_mixin.py:112} WARNING -   File "/home/nineleaps/.local/lib/python3.6/site-packages/airflow/jobs/base_job.py", line 221, in run
    self._execute()
[2020-06-05 13:07:29,792] {logging_mixin.py:112} WARNING -   File "/home/nineleaps/.local/lib/python3.6/site-packages/airflow/jobs/local_task_job.py", line 95, in _execute
    self.task_runner.start()
[2020-06-05 13:07:29,793] {logging_mixin.py:112} WARNING -   File "/home/nineleaps/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 42, in start
    self.process = self._start_by_fork()
[2020-06-05 13:07:29,793] {logging_mixin.py:112} WARNING -   File "/home/nineleaps/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 81, in _start_by_fork
    args.func(args, dag=self.dag)
[2020-06-05 13:07:29,793] {logging_mixin.py:112} WARNING -   File "/home/nineleaps/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 75, in wrapper
    return f(*args, **kwargs)
[2020-06-05 13:07:29,793] {logging_mixin.py:112} WARNING -   File "/home/nineleaps/.local/lib/python3.6/site-packages/airflow/bin/cli.py", line 545, in run
    _run(args, dag, ti)
[2020-06-05 13:07:29,793] {logging_mixin.py:112} WARNING -   File "/home/nineleaps/.local/lib/python3.6/site-packages/airflow/bin/cli.py", line 465, in _run
    pool=args.pool,
[2020-06-05 13:07:29,793] {logging_mixin.py:112} WARNING -   File "/home/nineleaps/.local/lib/python3.6/site-packages/airflow/utils/db.py", line 74, in wrapper
    return func(*args, **kwargs)
[2020-06-05 13:07:29,793] {logging_mixin.py:112} WARNING -   File "/home/nineleaps/.local/lib/python3.6/site-packages/airflow/sentry.py", line 144, in wrapper
    return func(task_instance, *args, session=session, **kwargs)
[2020-06-05 13:07:29,793] {logging_mixin.py:112} WARNING -   File "/home/nineleaps/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
[2020-06-05 13:07:29,793] {logging_mixin.py:112} WARNING -   File "/home/nineleaps/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
[2020-06-05 13:07:29,793] {logging_mixin.py:112} WARNING -   File "/home/nineleaps/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2020-06-05 13:07:29,794] {logging_mixin.py:112} WARNING -   File "/home/nineleaps/airflow/dags/Covid_India_SampleDag.py", line 70, in source_to_csv
    data = get_covid_data()
[2020-06-05 13:07:29,794] {logging_mixin.py:112} WARNING -   File "/home/nineleaps/airflow/dags/Covid_India_SampleDag.py", line 62, in get_covid_data
    confirmed_case_df = get_confirmed_cases()
[2020-06-05 13:07:29,794] {logging_mixin.py:112} WARNING -   File "/home/nineleaps/airflow/dags/Covid_India_SampleDag.py", line 46, in get_confirmed_cases
    logging.error("Error: ",err)
[2020-06-05 13:07:29,794] {logging_mixin.py:112} WARNING -   File "/usr/lib/python3.6/logging/__init__.py", line 1869, in error
    root.error(msg, *args, **kwargs)
[2020-06-05 13:07:29,794] {logging_mixin.py:112} WARNING -   File "/usr/lib/python3.6/logging/__init__.py", line 1337, in error
    self._log(ERROR, msg, args, **kwargs)
[2020-06-05 13:07:29,794] {logging_mixin.py:112} WARNING -   File "/usr/lib/python3.6/logging/__init__.py", line 1444, in _log
    self.handle(record)
[2020-06-05 13:07:29,794] {logging_mixin.py:112} WARNING -   File "/usr/lib/python3.6/logging/__init__.py", line 1454, in handle
    self.callHandlers(record)
[2020-06-05 13:07:29,794] {logging_mixin.py:112} WARNING -   File "/home/nineleaps/.local/lib/python3.6/site-packages/sentry_sdk/integrations/logging.py", line 83, in sentry_patched_callhandlers
    return old_callhandlers(self, record)
[2020-06-05 13:07:29,794] {logging_mixin.py:112} WARNING - Message: 'Error: '
Arguments: ('\x1b[1m404 Client Error: Not Found for url: https://api.covid19india.org/states_daily.jso\x1b[0m',)
[2020-06-05 13:07:39,272] {logging_mixin.py:112} INFO - [2020-06-05 13:07:39,271] {local_task_job.py:103} INFO - Task exited with return code 0
